#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH

transformix -def ../data/copd2/copd2_300_iBH_xyz_r1_elastix.txt -out ../registration-results/par0049/copd2/ -tp ../registration-results/par0049/copd2/TransformParameters.0.txt
transformix -def ../data/copd4/copd4_300_iBH_xyz_r1_elastix.txt -out ../registration-results/par0049/copd4/ -tp ../registration-results/par0049/copd4/TransformParameters.0.txt
transformix -def ../data/copd3/copd3_300_iBH_xyz_r1_elastix.txt -out ../registration-results/par0049/copd3/ -tp ../registration-results/par0049/copd3/TransformParameters.0.txt
transformix -def ../data/copd1/copd1_300_iBH_xyz_r1_elastix.txt -out ../registration-results/par0049/copd1/ -tp ../registration-results/par0049/copd1/TransformParameters.0.txt


