#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH

elastix -f ../data/./copd2/copd2_iBHCT.nii.gz -m ../data/./copd2/copd2_eBHCT.nii.gz -out ../registration-results/Par0035-NC-ASGD/copd2/ -p ../parameter_files/Par0035.SPREAD.NC.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd2/copd2_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-NC-ASGD/copd2/ -tp ../registration-results/Par0035-NC-ASGD/copd2/TransformParameters.1.txt
elastix -f ../data/./copd4/copd4_iBHCT.nii.gz -m ../data/./copd4/copd4_eBHCT.nii.gz -out ../registration-results/Par0035-NC-ASGD/copd4/ -p ../parameter_files/Par0035.SPREAD.NC.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd4/copd4_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-NC-ASGD/copd4/ -tp ../registration-results/Par0035-NC-ASGD/copd4/TransformParameters.1.txt
elastix -f ../data/./copd3/copd3_iBHCT.nii.gz -m ../data/./copd3/copd3_eBHCT.nii.gz -out ../registration-results/Par0035-NC-ASGD/copd3/ -p ../parameter_files/Par0035.SPREAD.NC.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd3/copd3_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-NC-ASGD/copd3/ -tp ../registration-results/Par0035-NC-ASGD/copd3/TransformParameters.1.txt
elastix -f ../data/./copd1/copd1_iBHCT.nii.gz -m ../data/./copd1/copd1_eBHCT.nii.gz -out ../registration-results/Par0035-NC-ASGD/copd1/ -p ../parameter_files/Par0035.SPREAD.NC.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd1/copd1_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-NC-ASGD/copd1/ -tp ../registration-results/Par0035-NC-ASGD/copd1/TransformParameters.1.txt

elastix -f ../data/./copd2/copd2_iBHCT.nii.gz -m ../data/./copd2/copd2_eBHCT.nii.gz -out ../registration-results/Par0035-MSD-ASGD/copd2/ -p ../parameter_files/Par0035.SPREAD.MSD.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd2/copd2_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MSD-ASGD/copd2/ -tp ../registration-results/Par0035-MSD-ASGD/copd2/TransformParameters.1.txt
elastix -f ../data/./copd4/copd4_iBHCT.nii.gz -m ../data/./copd4/copd4_eBHCT.nii.gz -out ../registration-results/Par0035-MSD-ASGD/copd4/ -p ../parameter_files/Par0035.SPREAD.MSD.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd4/copd4_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MSD-ASGD/copd4/ -tp ../registration-results/Par0035-MSD-ASGD/copd4/TransformParameters.1.txt
elastix -f ../data/./copd3/copd3_iBHCT.nii.gz -m ../data/./copd3/copd3_eBHCT.nii.gz -out ../registration-results/Par0035-MSD-ASGD/copd3/ -p ../parameter_files/Par0035.SPREAD.MSD.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd3/copd3_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MSD-ASGD/copd3/ -tp ../registration-results/Par0035-MSD-ASGD/copd3/TransformParameters.1.txt
elastix -f ../data/./copd1/copd1_iBHCT.nii.gz -m ../data/./copd1/copd1_eBHCT.nii.gz -out ../registration-results/Par0035-MSD-ASGD/copd1/ -p ../parameter_files/Par0035.SPREAD.MSD.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGD.txt
transformix -def ../data/copd1/copd1_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MSD-ASGD/copd1/ -tp ../registration-results/Par0035-MSD-ASGD/copd1/TransformParameters.1.txt

elastix -f ../data/./copd2/copd2_iBHCT.nii.gz -m ../data/./copd2/copd2_eBHCT.nii.gz -out ../registration-results/Par0035-MI-ASGDPrime/copd2/ -p ../parameter_files/Par0035.SPREAD.MI.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGDPrime.txt
transformix -def ../data/copd2/copd2_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MI-ASGDPrime/copd2/ -tp ../registration-results/Par0035-MI-ASGDPrime/copd2/TransformParameters.1.txt
elastix -f ../data/./copd4/copd4_iBHCT.nii.gz -m ../data/./copd4/copd4_eBHCT.nii.gz -out ../registration-results/Par0035-MI-ASGDPrime/copd4/ -p ../parameter_files/Par0035.SPREAD.MI.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGDPrime.txt
transformix -def ../data/copd4/copd4_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MI-ASGDPrime/copd4/ -tp ../registration-results/Par0035-MI-ASGDPrime/copd4/TransformParameters.1.txt
elastix -f ../data/./copd3/copd3_iBHCT.nii.gz -m ../data/./copd3/copd3_eBHCT.nii.gz -out ../registration-results/Par0035-MI-ASGDPrime/copd3/ -p ../parameter_files/Par0035.SPREAD.MI.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGDPrime.txt
transformix -def ../data/copd3/copd3_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MI-ASGDPrime/copd3/ -tp ../registration-results/Par0035-MI-ASGDPrime/copd3/TransformParameters.1.txt
elastix -f ../data/./copd1/copd1_iBHCT.nii.gz -m ../data/./copd1/copd1_eBHCT.nii.gz -out ../registration-results/Par0035-MI-ASGDPrime/copd1/ -p ../parameter_files/Par0035.SPREAD.MI.af.0.txt -p ../parameter_files/Par0035.SPREAD.MI.bs.1.ASGDPrime.txt
transformix -def ../data/copd1/copd1_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0035-MI-ASGDPrime/copd1/ -tp ../registration-results/Par0035-MI-ASGDPrime/copd1/TransformParameters.1.txt



