#!/bin/bash
export DYLD_LIBRARY_PATH=/Applications/elastix_macosx64_v4.8/lib:$DYLD_LIBRARY_PATH


elastix -f ../data/./copd1/copd1_iBHCT.nii.gz -fMask ../data/./copd1/copd1_iBHCT_mask.nii.gz -m ../data/./copd1/copd1_eBHCT.nii.gz -mMask ../data/./copd1/copd1_eBHCT_mask.nii.gz -out ../registration-results/Par0011-mask/copd1/ -p ../parameter_files/Parameters.Par0011.affine-working.txt -p ../parameter_files/Parameters.Par0011.bspline1-working.txt
transformix -def ../data/copd1/copd1_300_iBH_xyz_r1_elastix.txt -out ../registration-results/Par0011-mask/copd1/ -tp ../registration-results/Par0011-mask/copd1/TransformParameters.1.txt
















